### ISSUE TITLE
.NET 8 WPF applications crash when calling GetElement

### ISSUE THREAD

**Issue by Rayffer** [WPF-Pilot/WpfPilot#1]
When attempting to retrieve an element to control it, click it or whatever, the application crashes and WpfPilot throws an exception, find the message and stack trace in the following:

>   Message: 
> Test method threw exception: 
> WpfPilot.Utility.Retry+RetryException: App has unexpectedly exited.
> 
>   Stack Trace: 
> Retry.With(Action action, Int32 retryIntervalMs, Int32 retryCount)
> NamedPipeClient.GetResponse(Object command)
> AppDriver.DoGetElement(Func`2 matcher)
> AppDriver.GetElement(Func`2 matcher, Int32 timeoutMs)

The code I am invoking is the following:

`sut.GetElement(element => element["Name"] == "MainIcon");`

I am setting up the application likewise:

        sut = AppDriver.Launch(
            new ProcessStartInfo
            {
                WorkingDirectory = @"..\..\..\..\TestHarness",
                FileName = @"..\..\..\..\TestHarness\ApplicationName.exe"
            });

The application works correctly and I can even control it if I debug and hit a breakpoint, but the moment I attempt to retrieve an element from the window, it simply fails to do so whereas downgrading to .NET 6 works wonderfully.

**Comment by ELanning** [comment]
Thanks for reporting this. Looks like a few things need to be updated to support .NET 8. I should be able to get to this within the next few days.

Apologies for the inconvenience.

**Comment by Rayffer** [comment]
No need to apologize, I would like to congratulate you on doing this piece of software instead. Quite cutting edge!

**Comment by ELanning** [comment]
This should be fixed in version `1.0.1`+
