### ISSUE TITLE
WebView2 Support Bounty - $1000

### ISSUE THREAD

**Issue by ELanning** [WPF-Pilot/WpfPilot#10]
Puppeteer can be injected into browser instances:
https://pptr.dev/guides/running-puppeteer-in-the-browser

We would like to support injecting Puppeteer into a `WebView2` WPF component and then control it using C# bindings.

Here is a toy example of how this could be architected: https://wpfpilot.dev/docs/custom-elements
Note, that is very rudimentary and only has a few commands.
We want a full fledged API that looks similar to Playwright or Puppeteer. Feel free to model the API off of either.

Reqs:
- [ ] Complete `WebView2Element` with full feature set.
	- [ ] Selectors.
	- [ ] Actors (click, type, etc).
	- [ ] Anything else essential.
- [ ] Basic set of unit tests for the above.

Injecting Puppeteer to control the `WebView2` component is not strictly required, if there are better implementations.

**Comment by omarsoufiane** [comment]
hello @ELanning  you can create a bounty on [BountyHub](https://www.bountyhub.dev) if no one solves your issue, you can retract it and get your money back.
we are a new startup and our community is growing day after day, I would be glad to assist you if you need any help.

**Comment by ELanning** [comment]
I would certainly not object if a bot posted it there for me on my behalf, but I do not have the bandwidth to post there myself.
Similar to how Google automatically scrapes and categorizes the web.

**Comment by aybanda** [comment]
@ELanning 
I'm interested in working on this issue 
can you assign this to me 
I can accept the bounty after the successful implementation

**Comment by omarsoufiane** [comment]
@ELanning It's a simple process you just have to copy and paste the link of this GitHub issue and it will be automatically imported.
However, it's mandatory that you create an account on bountyhub, because you will be the one to review the pull request and accept/decline the bounty claims made by other users.

**Comment by ELanning** [comment]
@aybanda I have assigned you. I'll consider you the owner of the bounty until it's completed or you cannot complete it for whatever reason.

Feel free to use: https://github.com/WPF-Pilot/WpfWebView2Sample as a starting point (has a test suite set up and a custom element skeleton).

**Comment by aybanda** [comment]
> @aybanda I have assigned you. I'll consider you the owner of the bounty until it's completed or you cannot complete it for whatever reason.
> 
> Feel free to use: https://github.com/WPF-Pilot/WpfWebView2Sample as a starting point (has a test suite set up and a custom element skeleton).

excuse me for the inconvenience unfortunately I'm unable to takeover the issue.

**Comment by ELanning** [comment]
Open for anyone else then.

**Comment by parthiv11** [comment]
@ELanning I would like to give it a try

**Comment by ELanning** [comment]
Hey parthiv11, I've assigned you. Good luck. Feel free to post here with any questions.

**Comment by nabby27** [comment]
Hi @ELanning, you can create bounties also on [Opire](https://app.opire.dev), the good thing is that you don't need to pay out until someone claims the bounty with a PR, we don't hold funds.

PS: I'm the co-founder, so if you need anything, feel free to contact me.

**Comment by rahat2134** [comment]
@ELanning Please assign this issue to me. I have experience working in puppeteer. I have completed a full-size project of the puppeteer. Maybe you can take a look at some of them - 
- [link1](https://github.com/oppia/oppia/pull/20669)
- [link2](https://github.com/oppia/oppia/pull/20512)
- [link3](https://github.com/oppia/oppia/pull/20203)
- [link4](https://github.com/oppia/oppia/pull/20431)

I am just giving some of the PR's.

I have a doc full of the whole implementation, whole workflow...

**Comment by ELanning** [comment]
@parthiv11 any objections? Were you still planning on doing this? No worries if your plate is too full at the moment.

**Comment by rahat2134** [comment]
@ELanning Please let me know, I will start this after getting assigned.

**Comment by ELanning** [comment]
@rahat2134 will do. @parthiv11 is still working on this I believe, but if he has to drop it, you will be first on the list.

**Comment by rahat2134** [comment]
I think @parthiv11 is not active..... We can wait for his reply for a few days more!

**Comment by parthiv11** [comment]
I am working on this @ELanning @rahat2134, but was busy in Hacktoberfest last month.

therefore got delay in this one

**Comment by rahat2134** [comment]
@parthiv11 If you feel like passing this one to me at any time, feel free to ping me. 
Thanks!

**Comment by ELanning** [comment]
UPDATE: I thought there was a version of puppeteer that could run in the browser like this:
```
<script src="puppeteer.js" />
```
But it looks like that's not the case. Either way we want an API like playwright or puppeteer that works without requiring changes to the `WebView2` component (by the developer). Eg
```
appDriver.GetElement<WebView2Element>(x => x.Type == "WebView2").ClickElementById("#htmlIdSample")
```

Should "just work"

**Comment by parthiv11** [comment]
@ELanning https://github.com/ChromiumDotNet/WebView2.DevTools.Dom
this could be helpful and suits what we need

**Comment by ELanning** [comment]
Ah yes, that looks interesting. This seems like it may be a lot more work than expected and thus inappropriate as a mere bounty task. @parthiv11 what are your thoughts on me paying you for whatever time you've put in and then closing this issue as out of scope for a bounty?

**Comment by parthiv11** [comment]
I appreciate the offer to compensate for the time invested so far. Closing the issue as out of scope for a bounty sounds fair and reasonable. Let me know how you'd like to proceed!

**Comment by ELanning** [comment]
Sounds good, feel free to email me the bill at cs@eriklanning.com

**Comment by parthiv11** [comment]
Since the task has not been completed, I believe it would be inappropriate to accept payment. Therefore, I would prefer to forgo it.

**Comment by ELanning** [comment]
Feel free to reach out if you change your mind - thanks!

**Comment by parthiv11** [comment]
@ELanning. I appreciate your offer, but I would prefer to forgo the payment at this time. Also, I am currently seeking internship opportunities and would be grateful if you could help or provide any leads in that regard. 

Thanks again
