### ISSUE TITLE
Cloud Runner Guide - $300 bounty

### ISSUE THREAD

**Issue by ELanning** [WPF-Pilot/WpfPilot#9]
If someone could figure out how to set up WPF Pilot tests on an Azure service or Github Actions such that it can be part of a CI/CD pipeline, I am offering a $300 bounty.

A brief list of bullet point steps should suffice. I will revise it into docs for everyone.

**Comment by parthiv11** [comment]
@ELanning is it open ?

i want to give it a try

**Comment by ELanning** [comment]
@parthiv11 still open. Thank you very much!

**Comment by parthiv11** [comment]
I will give it a try and get back to you

**Comment by parthiv11** [comment]
@ELanning 

I tried GitHub actions.

https://github.com/parthiv11/PaymentCalculator/actions/runs/10961177199/job/30437492438

check it and let me know I am correct or wrong

**Comment by ELanning** [comment]
Hmm, very nice work. How would you like to be paid? Have a PayPal?

**Comment by parthiv11** [comment]
Thank you @ELanning 

GitHub sponsorship will work for me,

**Comment by parthiv11** [comment]
If there’s anything else I can help you with, please let me know.

**Comment by ELanning** [comment]
> Through GitHub sponsorship will work for me,

Done 👍

> If there’s anything else I can help you with, please let me know.

Will do, thanks.
